name: Angular Build

# Trigger the workflow on push or pull requests to the master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # Add more Node.js versions if needed
        # node-version: [14.x, 16.x, 17.x]
    steps:
      # Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm run test:ci

      # Build
      - name: Build
        run: npm run build
